# Generated by Django 5.0.14 on 2026-08-26 22:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='restaurant.branch')),
            ],
            options={
                'db_table': 'restaurant_floors',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('table_number', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('shape', models.CharField(choices=[('ROUND', 'Round'), ('SQUARE', 'Square'), ('RECTANGLE', 'Rectangle'), ('BOOTH', 'Booth')], default='SQUARE', max_length=20)),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('BILLED', 'Billed'), ('RESERVED', 'Reserved'), ('DIRTY', 'Needs Cleaning')], default='VACANT', max_length=20)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('assigned_server', models.CharField(blank=True, default='', max_length=100)),
                ('current_guest_count', models.PositiveIntegerField(default=0)),
                ('current_order_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='tables.floor')),
            ],
            options={
                'db_table': 'restaurant_tables',
                'ordering': ['table_number'],
            },
        ),
    ]
