# Generated by Django 5.0.14 on 2026-09-01 20:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vip_tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold VIP'), ('PLATINUM', 'Platinum Elite')], default='BRONZE', max_length=20)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('visit_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('dietary_tags', models.CharField(blank=True, default='', max_length=200)),
                ('last_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(default='General Produce', max_length=80)),
                ('unit', models.CharField(default='KG', max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('supplier_name', models.CharField(blank=True, default='Primary Wholesale', max_length=120)),
                ('last_restocked', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='utensils', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_selection', models.IntegerField(default=0)),
                ('max_selection', models.IntegerField(default=1)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin / Owner'), ('MANAGER', 'General Manager'), ('CASHIER', 'Head Cashier'), ('WAITER', 'Floor Captain / Waiter'), ('CHEF', 'Head Chef / Kitchen Staff'), ('DRIVER', 'Logistics Courier')], default='CASHIER', max_length=20)),
                ('pin_code', models.CharField(default='1234', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('value_json', models.JSONField(default=dict)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(default=4)),
                ('shape', models.CharField(default='SQUARE', max_length=20)),
                ('pos_x', models.IntegerField(default=50)),
                ('pos_y', models.IntegerField(default=50)),
                ('width', models.IntegerField(default=90)),
                ('height', models.IntegerField(default=90)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('BILL_REQUESTED', 'Bill Requested')], default='AVAILABLE', max_length=20)),
                ('current_order_id', models.IntegerField(blank=True, null=True)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('guest_count', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.floorsection')),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sku', models.CharField(blank=True, default='', max_length=50)),
                ('prep_time_minutes', models.IntegerField(default=12)),
                ('station', models.CharField(choices=[('ALL', 'All Stations'), ('GRILL', 'Grill & Steaks'), ('FRYER', 'Fryer & Apps'), ('ASSEMBLY', 'Pantry & Assembly'), ('BAR', 'Beverage & Bar')], default='GRILL', max_length=20)),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('is_kiosk_featured', models.BooleanField(default=False)),
                ('calories', models.IntegerField(blank=True, default=0)),
                ('allergens', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.menucategory')),
            ],
        ),
        migrations.CreateModel(
            name='ModifierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_default', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.modifiergroup')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True)),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Dine-in'), ('TAKEOUT', 'Takeout / Pickup'), ('DELIVERY', 'Home Delivery'), ('KIOSK', 'Self Kiosk')], default='DINE_IN', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'In Kitchen'), ('READY', 'Ready for Serving'), ('SERVED', 'Served'), ('COMPLETED', 'Completed & Paid'), ('CANCELLED', 'Cancelled / Void')], default='PENDING', max_length=20)),
                ('guest_count', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit / Debit Card'), ('POINTS', 'Loyalty Points'), ('SPLIT', 'Split Bill'), ('PENDING', 'Pending Payment')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20)),
                ('special_instructions', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.customer')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.diningtable')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_orders', to='api.staffmember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COOKING', 'Cooking'), ('READY', 'Ready'), ('SERVED', 'Served'), ('VOID', 'Voided')], default='PENDING', max_length=20)),
                ('station', models.CharField(default='GRILL', max_length=20)),
                ('selected_modifiers', models.JSONField(blank=True, default=list)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Stock In / Purchase'), ('USAGE', 'Kitchen Usage'), ('WASTE', 'Spoilage / Wastage'), ('ADJUSTMENT', 'Audit Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.inventoryitem')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staffmember')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=40)),
                ('customer_name', models.CharField(default='Guest', max_length=100)),
                ('delivery_status', models.CharField(choices=[('UNASSIGNED', 'Pending Assignment'), ('ASSIGNED', 'Assigned to Courier'), ('PICKED_UP', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed / Returned')], default='UNASSIGNED', max_length=20)),
                ('estimated_minutes', models.IntegerField(default=30)),
                ('driver_notes', models.TextField(blank=True, default='')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='api.order')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='api.staffmember')),
            ],
        ),
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=300.0, max_digits=10)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_card_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.staffmember')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='api.menuitem')),
                ('modifier_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modifiergroup')),
            ],
            options={
                'unique_together': {('menu_item', 'modifier_group')},
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, default=0.1, max_digits=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='api.inventoryitem')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='api.menuitem')),
            ],
            options={
                'unique_together': {('menu_item', 'inventory_item')},
            },
        ),
    ]
