# Generated by Django 5.0.14 on 2026-09-01 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_airecommendation_branch_businesstarget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work / Office'), ('FAMILY', 'Family / Parents'), ('OTHER', 'Other')], default='HOME', max_length=20)),
                ('city', models.CharField(default='Cairo', max_length=80)),
                ('area', models.CharField(default='New Cairo', max_length=100)),
                ('street', models.CharField(max_length=150)),
                ('building', models.CharField(blank=True, default='', max_length=50)),
                ('floor', models.CharField(blank=True, default='', max_length=30)),
                ('apartment', models.CharField(blank=True, default='', max_length=30)),
                ('landmark', models.CharField(blank=True, default='', max_length=150)),
                ('instructions', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('DELIVERY', 'Delivery Note'), ('FOOD_PREFERENCE', 'Food & Dietary Preference'), ('VIP', 'VIP / Service Touchpoint'), ('ADDRESS', 'Address Guidance'), ('OTHER', 'Other Note')], default='DELIVERY', max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(default='Cairo', max_length=80)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=30.0, max_digits=8)),
                ('estimated_minutes', models.IntegerField(default=35)),
                ('min_order_free_delivery', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_order_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='normalized_secondary_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='secondary_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='api.customer'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['normalized_phone'], name='api_custome_normali_f041ab_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='api_custome_name_99a87e_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_order_at'], name='api_custome_last_or_7903ac_idx'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.customer'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='customer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='api.customeraddress'),
        ),
        migrations.AddField(
            model_name='customernote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staffmember'),
        ),
        migrations.AddField(
            model_name='customernote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notes', to='api.customer'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='api.deliveryzone'),
        ),
    ]
