# Generated by Django 5.0.14 on 2026-09-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customeraddress_customernote_deliveryzone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
