# Generated by Django 5.0.14 on 2026-09-02 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_menucategory_name_ar_menuitem_description_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_en', models.CharField(max_length=80)),
                ('name_ar', models.CharField(blank=True, default='', max_length=80)),
                ('sla_minutes', models.IntegerField(default=12)),
                ('display_color', models.CharField(default='#f2ca50', max_length=30)),
                ('priority_level', models.CharField(default='NORMAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('screen_route', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='station',
            field=models.CharField(choices=[('ALL', 'All Stations'), ('PIZZA', 'Pizza'), ('SANDWICH', 'Sandwich & Burgers'), ('GRILL', 'Grill & Steaks'), ('FRYER', 'Fryer & Sides'), ('BAR', 'Beverage & Bar'), ('DESSERT', 'Dessert & Pastry'), ('ASSEMBLY', 'Pantry & Assembly')], default='GRILL', max_length=20),
        ),
        migrations.CreateModel(
            name='PrinterDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('printer_type', models.CharField(default='KITCHEN', max_length=30)),
                ('connection_type', models.CharField(default='NETWORK', max_length=30)),
                ('ip_address', models.CharField(default='192.168.1.100', max_length=45)),
                ('port', models.IntegerField(default=9100)),
                ('paper_width', models.CharField(default='80MM', max_length=10)),
                ('status', models.CharField(default='ONLINE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_print', models.BooleanField(default=True)),
                ('copies', models.IntegerField(default=1)),
                ('bilingual_mode', models.BooleanField(default=True)),
                ('header_text', models.CharField(blank=True, default="L'ETOILE HAUTE CUISINE", max_length=200)),
                ('footer_text', models.CharField(blank=True, default='Master Kitchen - Culinary Precision', max_length=200)),
                ('last_ping', models.DateTimeField(auto_now=True)),
                ('backup_printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failover_for', to='api.printerdevice')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='api.stationprofile')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenPrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=40, unique=True)),
                ('station_code', models.CharField(default='KITCHEN', max_length=30)),
                ('ticket_type', models.CharField(default='KITCHEN_TICKET', max_length=30)),
                ('items_payload', models.JSONField(default=list)),
                ('rendered_text_en', models.TextField(blank=True, default='')),
                ('rendered_text_ar', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='api.order')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.printerdevice')),
            ],
        ),
        migrations.CreateModel(
            name='PrinterRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rule_level', models.CharField(default='STATION', max_length=20)),
                ('station_code', models.CharField(blank=True, default='GRILL', max_length=30)),
                ('order_type', models.CharField(blank=True, default='', max_length=20)),
                ('priority', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('backup_printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_rules', to='api.printerdevice')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_rules', to='api.menucategory')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_rules', to='api.menuitem')),
                ('primary_printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_rules', to='api.printerdevice')),
            ],
        ),
    ]
