# Generated by Django 5.0.14 on 2026-09-02 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stationprofile_alter_menuitem_station_printerdevice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, default='', max_length=100)),
                ('cuisine_type', models.CharField(default='Contemporary', max_length=80)),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('theme_color', models.CharField(default='#f2ca50', max_length=30)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('order_count', models.IntegerField(default=0)),
                ('cogs_percentage', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('profit_lift_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Noir Hospitality Group', max_length=150)),
                ('operating_tenant_code', models.CharField(default='TENANT-001', max_length=50)),
                ('business_mode', models.CharField(choices=[('FAST_FOOD', 'QSR / Fast Casual'), ('FINE_DINING', 'Fine Dining'), ('CASUAL_DINING', 'Casual Dining'), ('CAFE', 'Cafe & Bakery'), ('PIZZERIA', 'Pizzeria'), ('BURGER', 'Burger House'), ('FOOD_TRUCK', 'Food Truck'), ('CLOUD_KITCHEN', 'Cloud Kitchen'), ('CATERING', 'Catering & Events'), ('DELIVERY_ONLY', 'Delivery Only'), ('MULTI_BRANCH', 'Multi-Branch'), ('FRANCHISE', 'Franchise Network')], default='FINE_DINING', max_length=30)),
                ('active_brand_count', models.IntegerField(default=3)),
                ('active_branch_count', models.IntegerField(default=4)),
                ('currency_code', models.CharField(default='USD', max_length=10)),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=14.0, max_digits=5)),
                ('service_charge_percentage', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('feature_flags', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CateringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_number', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=120)),
                ('client_phone', models.CharField(max_length=50)),
                ('client_email', models.CharField(blank=True, default='', max_length=120)),
                ('event_date', models.DateTimeField()),
                ('guest_count', models.IntegerField(default=50)),
                ('venue_name', models.CharField(default='Grand Ballroom B', max_length=200)),
                ('venue_type', models.CharField(default='ON_SITE', max_length=50)),
                ('package_name', models.CharField(default='Royal Executive Gala', max_length=120)),
                ('status', models.CharField(default='CONFIRMED', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('assigned_head_chef', models.CharField(blank=True, default='Chef Antoine Dubois', max_length=100)),
                ('staff_assigned_count', models.IntegerField(default=8)),
                ('menu_summary', models.TextField(blank=True, default='')),
                ('special_instructions', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='diningtable',
            name='coursing_status',
            field=models.CharField(blank=True, default='STARTER_HOLD', max_length=30),
        ),
        migrations.AddField(
            model_name='diningtable',
            name='is_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningtable',
            name='seats_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diningtable',
            name='zone',
            field=models.CharField(blank=True, default='Main Dining', max_length=50),
        ),
        migrations.AlterField(
            model_name='diningtable',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('BILL_REQUESTED', 'Bill Requested'), ('CLEANING', 'Cleaning'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='MenuPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='DINE_IN', max_length=30)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjusted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('happy_hour_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_happy_hour_active', models.BooleanField(default=False)),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=68.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='api.menuitem')),
            ],
        ),
    ]
