# Generated by Django 5.0.14 on 2026-09-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_brand_businessconfig_cateringevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin / Owner'), ('MANAGER', 'General Manager'), ('CASHIER', 'Head Cashier'), ('WAITER', 'Floor Captain / Waiter'), ('CHEF', 'Head Chef / Kitchen Staff'), ('DRIVER', 'Logistics Courier'), ('PACKING', 'Packing & Dispatch'), ('BAR', 'Bar & Beverage'), ('INVENTORY', 'Inventory Controller'), ('CALL_CENTER', 'Call Center Agent'), ('ACCOUNTING', 'Financial Accountant'), ('HR', 'HR & People Operations')], default='CASHIER', max_length=20),
        ),
    ]
