# Generated by Django 5.0.14 on 2026-09-29 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('ORDER_CREATED', 'New Order Placed'), ('ORDER_READY', 'Kitchen Order Ready'), ('PAYMENT_RECEIVED', 'Payment Settled'), ('SHIFT_ALERT', 'Shift & Drawer Alert'), ('LOW_STOCK', 'Low Stock Warning'), ('SYSTEM_NOTICE', 'System Notice')], default='SYSTEM_NOTICE', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link_url', models.CharField(blank=True, default='', max_length=255)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurant_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
