# Generated by Django 5.0.14 on 2026-09-29 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('ORDER_CREATE', 'Create Order'), ('ORDER_STATUS', 'Update Order Status'), ('ORDER_CANCEL', 'Cancel Order'), ('PAYMENT_PROCESSED', 'Process Payment'), ('PAYMENT_REFUND', 'Refund Payment'), ('SHIFT_OPEN', 'Open Shift Drawer'), ('SHIFT_CLOSE', 'Close Shift Drawer'), ('PRICE_OVERRIDE', 'Manager Price Override'), ('DISCOUNT_APPLIED', 'Discount Applied'), ('ROLE_MODIFIED', 'User Role Modified'), ('SYSTEM_CONFIG', 'System Setting Changed')], max_length=40)),
                ('module', models.CharField(default='SYSTEM', max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurant_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
