# Generated by Django 5.0.14 on 2026-08-26 22:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('DIRECT', 'Direct Online'), ('DOORDASH', 'DoorDash'), ('UBEREATS', 'UberEats'), ('DELIVEROO', 'Deliveroo')], default='DIRECT', max_length=30)),
                ('stage', models.CharField(choices=[('RECEIVED', 'Received'), ('PREPARING', 'In Kitchen'), ('READY_FOR_PICKUP', 'Ready for Driver'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed Delivery')], default='RECEIVED', max_length=30)),
                ('delivery_address', models.TextField()),
                ('customer_notes', models.TextField(blank=True, default='')),
                ('estimated_arrival_minutes', models.PositiveIntegerField(default=35)),
                ('tracking_url', models.URLField(blank=True, default='')),
            ],
            options={
                'db_table': 'delivery_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(default='Motorcycle', max_length=50)),
                ('license_plate', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('current_status', models.CharField(default='AVAILABLE', max_length=30)),
            ],
            options={
                'db_table': 'delivery_drivers',
                'ordering': ['name'],
            },
        ),
    ]
