# Generated by Django 5.0.14 on 2026-08-26 22:54

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze Member'), ('SILVER', 'Silver VIP'), ('GOLD', 'Gold VIP'), ('PLATINUM', 'Platinum Elite')], default='BRONZE', max_length=20)),
                ('loyalty_points', models.PositiveIntegerField(default=100)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_visits', models.PositiveIntegerField(default=1)),
                ('favorite_dish', models.CharField(blank=True, default='Margherita D.O.P.', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'restaurant_customers',
                'ordering': ['-total_spent', 'name'],
            },
        ),
    ]
